FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache python3 make g++

COPY backend/package*.json ./backend/
RUN cd backend && npm install --omit=dev

COPY backend ./backend

EXPOSE 3000

CMD ["node", "backend/src/server.js"]
