ALTER TABLE order_shipping
  ADD COLUMN IF NOT EXISTS provider_name_snapshot VARCHAR(160),
  ADD COLUMN IF NOT EXISTS service_name_snapshot VARCHAR(160),
  ADD COLUMN IF NOT EXISTS rate_version_snapshot VARCHAR(120),
  ADD COLUMN IF NOT EXISTS notes TEXT,
  ADD COLUMN IF NOT EXISTS shipped_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS delivered_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS rate_currency VARCHAR(10) NOT NULL DEFAULT 'MXN';
